---
title: "440ProjectFinalReport"
output: pdf_document
---

Canada data
```{r}
data.confirmed <- read.csv("time_series_covid19_confirmed_global.csv", sep=",", header = TRUE)
data.confirmed.canada <- data.confirmed[data.confirmed[,"Country.Region"]=="Italy",]
data.confirmed.test <- colSums(data.confirmed.canada[,(ncol(data.confirmed.canada)-39):ncol(data.confirmed.canada)])
data.confirmed.train <- colSums(data.confirmed.canada[,(ncol(data.confirmed.canada)-29):ncol(data.confirmed.canada)-10])

data.recovered <- read.csv("time_series_covid19_recovered_global.csv", sep=",", header = TRUE)
data.recovered.canada <- data.recovered[data.recovered[,"Country.Region"]=="Italy",]
data.recovered.test <- colSums(data.recovered.canada[,(ncol(data.recovered.canada)-39):ncol(data.recovered.canada)])
data.recovered.train <- colSums(data.recovered.canada[,(ncol(data.recovered.canada)-29):ncol(data.recovered.canada)-10])

data.death <- read.csv("time_series_covid19_deaths_global.csv", sep=",", header = TRUE)
data.death.canada <- data.death[data.death[,"Country.Region"]=="Italy",]
data.death.test <- colSums(data.death.canada[,(ncol(data.death.canada)-39):ncol(data.death.canada)])
data.death.train <- colSums(data.death.canada[,(ncol(data.death.canada)-29):ncol(data.death.canada)-10])
```

```{r}
# installation of usethis, devtools and roxygen2 are required. i.e. install.pacakages("devtools")
library(reticulate)
require(coronaModel)
os <- import("os")
# use_python("/usr/local/bin/python3.7")
# py_install("scipy")
source_python('seir_main.py')
res <- searchBestParam(30000000, 1100, data.confirmed.test, data.death.test, data.recovered.test) #init S, range of init E, confirmed data, death data, recovered data
param <- res[1][[1]]
E <- res[2][[1]]
I <- data.confirmed.train[1]
D <- data.death.train[1]
C <- data.recovered.train[1]
a1 = param$alpha1
a2 = param$alpha2
b = param$beta
s = param$sigma
g = param$gamma

pred <- seir_fit(40,a1,a2,b,s,g,E, I, D, C)
data <- list(I=data.confirmed.test, D=data.death.test, C=data.recovered.test)
seir_plot(pred, data)
```

test estimate
```{r}
E <- 150
I <- data.confirmed.train[1]
D <- data.death.train[1]
C <- data.recovered.train[1]
a1 = 0.5
a2 = 0.1
b = 0.3
s = 0.4
g = 0.5
pred <- sier_predict(35,a1,a2,b,s,g,E, I, D, C)
sier_plot(pred, data)
res <- searchBestParam(30000000, 1100, pred$I, pred$D, pred$C)
param <- res[1][[1]]
new_E <- res[2][[1]]
param
new_E
```

